name: Basic Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Warsaw

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm format:check

      - name: Check types
        run: pnpm types

      - name: Check linting
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Upload coverage results
        uses: codecov/codecov-action@v4
        with:
          files: ./apps/api/coverage/lcov.info
