name: Docker Production

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Commit hash to deploy"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  COMMIT_HASH: ${{ github.event.inputs.commit_hash }}

jobs:
  deploy-production:
    name: Rollout to Production
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ""

      - name: Update Kubernetes Deployment
        run: |
          echo "Updating Kubernetes Deployment with image: ghcr.io/fwu-de/telli-api:${{ env.COMMIT_HASH }}"
          kubectl set image deployment/telli-api-prod \
            telli-api-prod=ghcr.io/fwu-de/telli-api:${{ env.COMMIT_HASH }}
          kubectl rollout restart deployment telli-api-prod
      - name: Wait for rollout to complete
        run: |
          echo "Waiting for rollout to complete"
          kubectl rollout status deployment/telli-api-prod
