name: Skip Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  skip:
    name: Skip Everything
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow intentionally does nothing and is skipped."
        if: ${{ false }}